language: python

python: 
    - "3.6"
    
install:
    - pip3 install cython numpy coveralls
    - python3 setup.py build_ext --inplace
    - python3 setup.py install

script:
    - python3 setup.py test

after_success:
    - coveralls
    